// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-mZmBR4hVQw9uOOg5wRLp3AHq2tS0B98',
    appId: '1:927511023655:web:80df020461746b0ebf7e02',
    messagingSenderId: '927511023655',
    projectId: 'health4u-292bd',
    authDomain: 'health4u-292bd.firebaseapp.com',
    storageBucket: 'health4u-292bd.firebasestorage.app',
    measurementId: 'G-HJ79YE0SBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-nU0g87x1-yLgbXTAcQfcYZUSEK8wppk',
    appId: '1:927511023655:android:e9bb6102e6e7ecc7bf7e02',
    messagingSenderId: '927511023655',
    projectId: 'health4u-292bd',
    storageBucket: 'health4u-292bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7VIjnILimVoSbvG7dh48EfmG4R6hpw1Q',
    appId: '1:927511023655:ios:6d44974d5b92f156bf7e02',
    messagingSenderId: '927511023655',
    projectId: 'health4u-292bd',
    storageBucket: 'health4u-292bd.firebasestorage.app',
    iosBundleId: 'com.example.health4u',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7VIjnILimVoSbvG7dh48EfmG4R6hpw1Q',
    appId: '1:927511023655:ios:6d44974d5b92f156bf7e02',
    messagingSenderId: '927511023655',
    projectId: 'health4u-292bd',
    storageBucket: 'health4u-292bd.firebasestorage.app',
    iosBundleId: 'com.example.health4u',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-mZmBR4hVQw9uOOg5wRLp3AHq2tS0B98',
    appId: '1:927511023655:web:12153a67dcdef14abf7e02',
    messagingSenderId: '927511023655',
    projectId: 'health4u-292bd',
    authDomain: 'health4u-292bd.firebaseapp.com',
    storageBucket: 'health4u-292bd.firebasestorage.app',
    measurementId: 'G-V9GRJYXV0D',
  );

}